server:
  port: 8001
eureka:
  instance:
    hostname: localhost
spring:
  application:
    name: student-service
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: 1213
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

